import type { ScenarioDescriptor, ScenarioState } from "./types";

export const initialState: ScenarioState = {
  eventId: "national_day_2026",
  eventName: "National Day 2026",
  stage: "DURING_EVENT",
  stageProgress: 0.62,
  eventClock: "19:42",
  elapsedLabel: "T+1h 12m",
  attendance: {
    current: 18240,
    capacity: 20000,
    fillRate: 0.912,
    arrivalVelocity: 240,
  },
  corridors: {
    A: { load: 0.42, forecast20min: 0.48, divertActive: false },
    B: { load: 0.35, forecast20min: 0.42, divertActive: false },
  },
  parking: { P1: 0.94, P2: 0.68, P3: 0.45, P4: 0.82 },
  parkingForecast12m: { P4: 0.99, P2: 0.78 },
  hotspots: [
    { zone: "gate_A", labelKey: "zone.gate_A", density: 0.42, trend: "STABLE", severity: "LOW" },
    { zone: "gate_B", labelKey: "zone.gate_B", density: 0.58, trend: "STABLE", severity: "MEDIUM" },
    { zone: "plaza_central", labelKey: "zone.plaza_central", density: 0.62, trend: "STABLE", severity: "MEDIUM" },
  ],
  psim: { activeIncidents: 2, critical: 0, lastEvent: "minor_lost_child_resolved" },
  weather: { tempC: 37, condition: "CLEAR", forecast60min: "CLEAR", forecastConfidence: 0.9 },
  overlays: { rain: false },
  vip: { active: false },
  kpi: {
    incidentResponseSec: 192,
    responseDeltaPct: -38,
    manualCoordSteps: 4.2,
    manualCoordDeltaPct: -44,
    proactiveRatio: [58, 42],
  },
};

export const scenarios: ScenarioDescriptor[] = [
  {
    key: "S01_GATE_B",
    number: "01",
    shortTitleKey: "scn.s01.short",
    longTitleKey: "scn.s01.long",
    ruleId: "EVT-CROWD-001",
    priority: "HIGH",
    outcomeKey: "scn.s01.outcome",
    tagKey: "scn.s01.tag",
  },
  {
    key: "S02_P4",
    number: "02",
    shortTitleKey: "scn.s02.short",
    longTitleKey: "scn.s02.long",
    ruleId: "EVT-PARK-002",
    priority: "MEDIUM",
    outcomeKey: "scn.s02.outcome",
    tagKey: "scn.s02.tag",
  },
  {
    key: "S03_MEDICAL",
    number: "03",
    shortTitleKey: "scn.s03.short",
    longTitleKey: "scn.s03.long",
    ruleId: "EVT-SEC-003",
    priority: "CRITICAL",
    outcomeKey: "scn.s03.outcome",
    tagKey: "scn.s03.tag",
  },
  {
    key: "S04_RAIN",
    number: "04",
    shortTitleKey: "scn.s04.short",
    longTitleKey: "scn.s04.long",
    ruleId: "EVT-WEATHER-001",
    priority: "HIGH",
    outcomeKey: "scn.s04.outcome",
    tagKey: "scn.s04.tag",
  },
  {
    key: "S05_VIP",
    number: "05",
    shortTitleKey: "scn.s05.short",
    longTitleKey: "scn.s05.long",
    ruleId: "EVT-VIP-001",
    priority: "HIGH",
    outcomeKey: "scn.s05.outcome",
    tagKey: "scn.s05.tag",
  },
];
